### PR TITLE
Dev.ng15

### PR DESCRIPTION
**Pull request by roedoejet**
This is an upgrade to Angular 15 which will make our lives much easier when moving Studio-Web to the monorepo. This is a draft PR for finishing the Angular checklist. I have currently completed everything [here](https://update.angular.io/?l=3&v=14.0-15.0) up until the last two checkpoints, namely:

- [x] In Angular Material v15, many of the components have been refactored to be based on the official Material Design Components for Web (MDC). This change affected the DOM and CSS classes of many components. [Read further](https://rc.material.angular.io/guide/mdc-migration)
- [x] After you update your application to v15, visually review your application and its interactions to ensure everything is working as it should.

So, while the app does start, the styling is broken, and will be until the above two are completed. Finally, the most annoying thing is that the [angular 15 version](https://github.com/shipshapecode/angular-shepherd/pull/1584) of shepherd JS has not been merged/released. This means we need to run `npm install --force` when installing. Shepherd appears to still work, but this is not great. Hopefully this is released soon.

### CODE REVIEW

**Comment by joanise** [comment]
I have completed the transition to NG 15, and finally gotten the unit tests to run (and pass). Someone else should do a visual inspection of the app and polish anything I didn't do quite right. It wasn't too painful to do, thankfully.

The unit tests pass, but there are a lot of warnings and error messages that get spewed out while they run, both on my terminal and in CI. At some point, those should get examined and hopefully fixed. That was already happening before this PR, though, so it's not related to the NG 15 upgrade.

**Review by joanise — APPROVED** [review]
With my changes, I recommend we upgrade this PR from a draft to a real one, get one more review on it, and then merge.

**Comment by joanise** [comment]
One thing I would still like to change: there is now some wasted space underneath the text input box for the RA text. That didn't used to be the case. It would be nice to remove that wasted space.
image
I mean the half inch or so (on my screen) at the bottom in this screen capture.

It would also be really nice to enable the user to make that input box bigger. The little corner thing is there suggesting you can, but I tried, it wasn't resizable with ng 14 and it still isn't with ng 15.

**Comment by roedoejet** [comment]
Looks good to me! I like the changes to the workflow removing the PR builds. I'd like to not forget about the `--force` flag, so maybe we can make an issue or something to keep an eye on shepherd for when an angular 15 release comes out?

**Pull request merged**
